services:
  app:
    build: ./.docker/app
    volumes:
      - ./src:/src:cached
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
